<?php

namespace ContainerAxl0Yx8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PMqLatoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PMqLato' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PMqLato'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'film' => ['privates', '.errored..service_locator.PMqLato.App\\Entity\\Film', NULL, 'Cannot autowire service ".service_locator.PMqLato": it references class "App\\Entity\\Film" but no such service exists.'],
        ], [
            'film' => 'App\\Entity\\Film',
        ]);
    }
}
