<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Film__CLASSMETADATA__' => 0,
'App__Entity__Favoris__CLASSMETADATA__' => 1,
'App__Entity__Serie__CLASSMETADATA__' => 2,
'App__Entity__User__CLASSMETADATA__' => 3,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Film',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Film',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\FilmRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nomFilm' => [
                            'fieldName' => 'nomFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'nom_film',
                        ],
                        'lienFilm' => [
                            'fieldName' => 'lienFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => 0,
                            'columnName' => 'lien_film',
                        ],
                        'notePresseFilm' => [
                            'fieldName' => 'notePresseFilm',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'note_presse_film',
                        ],
                        'datefilm' => [
                            'fieldName' => 'datefilm',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'datefilm',
                        ],
                        'resumeFilm' => [
                            'fieldName' => 'resumeFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 10000,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'resume_film',
                        ],
                        'adresseImageCouvertureFilm' => [
                            'fieldName' => 'adresseImageCouvertureFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'adresse_image_couverture_film',
                        ],
                        'realisateurFilm' => [
                            'fieldName' => 'realisateurFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'realisateur_film',
                        ],
                        'sommeilFilm' => [
                            'fieldName' => 'sommeilFilm',
                            'type' => 'boolean',
                            'scale' => 0,
                            'length' => 5,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'sommeil_film',
                        ],
                        'genre' => [
                            'fieldName' => 'genre',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'genre',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom_film' => 'nomFilm',
                        'lien_film' => 'lienFilm',
                        'note_presse_film' => 'notePresseFilm',
                        'datefilm' => 'datefilm',
                        'resume_film' => 'resumeFilm',
                        'adresse_image_couverture_film' => 'adresseImageCouvertureFilm',
                        'realisateur_film' => 'realisateurFilm',
                        'sommeil_film' => 'sommeilFilm',
                        'genre' => 'genre',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nomFilm' => 'nom_film',
                        'lienFilm' => 'lien_film',
                        'notePresseFilm' => 'note_presse_film',
                        'datefilm' => 'datefilm',
                        'resumeFilm' => 'resume_film',
                        'adresseImageCouvertureFilm' => 'adresse_image_couverture_film',
                        'realisateurFilm' => 'realisateur_film',
                        'sommeilFilm' => 'sommeil_film',
                        'genre' => 'genre',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'film',
                    ],
                ],
                'associationMappings' => [
                    [
                        'favorisFilm' => [
                            'fieldName' => 'favorisFilm',
                            'joinTable' => [
                                'name' => 'film_user',
                                'joinColumns' => [
                                    [
                                        'name' => 'film_id',
                                        'referencedColumnName' => 'id',
                                        'onDelete' => 'CASCADE',
                                    ],
                                ],
                                'inverseJoinColumns' => [
                                    [
                                        'name' => 'user_id',
                                        'referencedColumnName' => 'id',
                                        'onDelete' => 'CASCADE',
                                    ],
                                ],
                            ],
                            'targetEntity' => 'App\\Entity\\User',
                            'mappedBy' => null,
                            'inversedBy' => 'films',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 8,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Film',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'joinTableColumns' => [
                                'film_id',
                                'user_id',
                            ],
                            'isOnDeleteCascade' => true,
                            'relationToSourceKeyColumns' => [
                                'film_id' => 'id',
                            ],
                            'relationToTargetKeyColumns' => [
                                'user_id' => 'id',
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Favoris',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Favoris',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\FavorisRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nomOeuvre' => [
                            'fieldName' => 'nomOeuvre',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_oeuvre',
                        ],
                        'type' => [
                            'fieldName' => 'type',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'type',
                        ],
                        'resumeFilm' => [
                            'fieldName' => 'resumeFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 10000,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'resume_film',
                        ],
                        'adresseImageCouvertureFilm' => [
                            'fieldName' => 'adresseImageCouvertureFilm',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'adresse_image_couverture_film',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom_oeuvre' => 'nomOeuvre',
                        'type' => 'type',
                        'resume_film' => 'resumeFilm',
                        'adresse_image_couverture_film' => 'adresseImageCouvertureFilm',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nomOeuvre' => 'nom_oeuvre',
                        'type' => 'type',
                        'resumeFilm' => 'resume_film',
                        'adresseImageCouvertureFilm' => 'adresse_image_couverture_film',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'favoris',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Serie',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Serie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SerieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nomSerie' => [
                            'fieldName' => 'nomSerie',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom_serie',
                        ],
                        'notePresseSerie' => [
                            'fieldName' => 'notePresseSerie',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'note_presse_serie',
                        ],
                        'dateserie' => [
                            'fieldName' => 'dateserie',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'dateserie',
                        ],
                        'resumeSerie' => [
                            'fieldName' => 'resumeSerie',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 100000,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'resume_serie',
                        ],
                        'adresseImageCouvertureSerie' => [
                            'fieldName' => 'adresseImageCouvertureSerie',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 70,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'adresse_image_couverture_serie',
                        ],
                        'realisateurSerie' => [
                            'fieldName' => 'realisateurSerie',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'realisateur_serie',
                        ],
                        'sommeilSerie' => [
                            'fieldName' => 'sommeilSerie',
                            'type' => 'boolean',
                            'scale' => 0,
                            'length' => 5,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'sommeil_serie',
                        ],
                        'genre' => [
                            'fieldName' => 'genre',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'genre',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom_serie' => 'nomSerie',
                        'note_presse_serie' => 'notePresseSerie',
                        'dateserie' => 'dateserie',
                        'resume_serie' => 'resumeSerie',
                        'adresse_image_couverture_serie' => 'adresseImageCouvertureSerie',
                        'realisateur_serie' => 'realisateurSerie',
                        'sommeil_serie' => 'sommeilSerie',
                        'genre' => 'genre',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nomSerie' => 'nom_serie',
                        'notePresseSerie' => 'note_presse_serie',
                        'dateserie' => 'dateserie',
                        'resumeSerie' => 'resume_serie',
                        'adresseImageCouvertureSerie' => 'adresse_image_couverture_serie',
                        'realisateurSerie' => 'realisateur_serie',
                        'sommeilSerie' => 'sommeil_serie',
                        'genre' => 'genre',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'serie',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\User',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'nom',
                        ],
                        'prenom' => [
                            'fieldName' => 'prenom',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'prenom',
                        ],
                        'datedenaissance' => [
                            'fieldName' => 'datedenaissance',
                            'type' => 'date',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'datedenaissance',
                        ],
                        'pays' => [
                            'fieldName' => 'pays',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'pays',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'email',
                        ],
                        'username' => [
                            'fieldName' => 'username',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'username',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'roles',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => 0,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => 0,
                            'columnName' => 'password',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'datedenaissance' => 'datedenaissance',
                        'pays' => 'pays',
                        'email' => 'email',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'nom',
                        'prenom' => 'prenom',
                        'datedenaissance' => 'datedenaissance',
                        'pays' => 'pays',
                        'email' => 'email',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'films' => [
                            'fieldName' => 'films',
                            'joinTable' => [],
                            'targetEntity' => 'App\\Entity\\Film',
                            'mappedBy' => 'favorisFilm',
                            'inversedBy' => null,
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 8,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\User',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
