<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwZ61ua\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwZ61ua/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQwZ61ua.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQwZ61ua\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQwZ61ua\App_KernelProdContainer([
    'container.build_hash' => 'QwZ61ua',
    'container.build_id' => '8378e951',
    'container.build_time' => 1623968447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwZ61ua');
