<?php

namespace ContainerQwZ61ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.PMqLato.App\Entity\Film' shared service.
     *
     * @return \App\Entity\Film
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PMqLato": it references class "App\\Entity\\Film" but no such service exists.');
    }
}
