<?php

namespace ContainerQwZ61ua;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SerieRepository' shared autowired service.
     *
     * @return \App\Repository\SerieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SerieRepository'] = new \App\Repository\SerieRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
